### ISSUE TITLE
bug: config not saving properly

### ISSUE THREAD

**Issue by evilryan** [adibarra/enchant-tweaker#25] opened 2024-01-24 01:25 UTC
### What does it do?

This is in a fabric server with no other enchant mods.

For example, I have set "/et config capmod_enabled true", then I set "/et config unbreaking 10" ET (even tried server restart), and then in-game, I do not ever see unbreaking 10 possible when trying to enchant a book or netherite tool/weapons. Nor am I able to combine for example two Unbreaking 3 books in an anvil, to attempt to get beyond Unbreaking 3. (I would expact combining two Unbreaking 3 books would get me to Unbreaking 4)

### Why add it?

I just need clarification/guidance on how this should be working.

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment] 2024-01-24 01:47
Hello! The higher levels won't show up in the enchanting table. However, they should appear when you try and combine them in an anvil like you said.

If this isn't happening then its probably a bug of some kind. I just jumped into a fresh server instance and tried it out but wasn't able to replicate this. So I'll need some more information from you.

1. What version of minecraft?
2. What is the mod's jar file name?
3. Can you attach the config file here (enchant-tweaker.properties)?
4. Can you attach a server logfile here?

These should help me narrow down the cause of the issue.

**Comment by adibarra** [comment] 2024-01-24 02:22
I think I found the issue. The fix will be in the next update (v1.4.9).
If that version doesn't work for you then please reopen the issue.

**Closed as completed** 2024-01-24 02:22 UTC
Labels: type/bug

**Comment by Epsilon2131O** [comment] 2024-12-25 11:58
Hi there! For anyone encountering this issue on the newest version of the mod, make sure you do it in a new world. Pre-existing worlds will show that things are configured correctly but sometimes not implement the functionality and behave as though the mod isn't present at all. I had this issue and fixed it by creating a new world and restarting the game.

As a quick aside in case adibarra sees this, I have a feature request as well.

It would be nice to add a tweak to this list for _allowing enchants on illegal items_. For instance the popular use case of putting **knockback on a stick**. It fits in perfectly with the currently present tweaks, would bring the number of tweaks present up to a rather "nice" 69, and would bring people to your mod as a one-stop shop to accomplish all of their enchant tweak needs instead of 2-3 alternatives with limited customization and functionality.

I am adding this mod to my modpack and currently looking for something with this functionality to use in conjunction with your mod but I see no reason it couldn't be a tweak in yours :) Thanks for your time and great mod!
