### ISSUE TITLE
bug: some settings don't save when using in-game commands

### ISSUE THREAD

**Issue by GillesDLT** [adibarra/enchant-tweaker#13] opened 2023-09-12 12:14 UTC
### What happened?

some enchantment settings such as protection and channeling are not saved, but when I restart the game the settings are (protection 7 and channeling 2 specifically).
whereas enchantments like blast protection 7 are.
I'd like to point out that if I make my settings in Creative, for example protection 7, and then go to Survival and get this enchantment on an object or a book
Then if I restart the game, I'll still have my enchantment at the level I want in survival, but I won't be able to get another one if I don't redo the settings. It's as if they were illegal enchantments.

### What should have happened?

I don't want to redo these settings every time I launch my game.

### What is the jar file name?

enchanttweaker-1.4.4+mc1.20-1.20.1.jar

### What Minecraft version?

Fabric 1.20.1

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment] 2023-09-18 06:32
Hello, thanks for the report!

I've been able to reproduce this bug, and I'll start looking into the cause. It seems the issue with saving changes to the settings only occurs when using the in-game commands. As a temporary workaround, you can directly edit the mod's config file while I work on a fix.

You also mentioned that books persist at higher than-allowed enchantment levels after changing settings. This is an intended behavior. The mod will **never** delete or modify any items.

**Comment by adibarra** [comment] 2023-09-18 17:02
It should be fixed now. The fix will be included in the next update (v1.4.5)

**Closed as completed** 2023-09-18 17:02 UTC
Labels: type/bug
